create schema if not exists public;

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

create or replace function public.set_data_atualizacao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_atualizacao = now();
	return new;
end;
$$;

create table if not exists public.usuarios (
	codusuario integer generated by default as identity primary key,
	usuario varchar(50) not null unique check (char_length(usuario) between 3 and 50),
	senha varchar(255) not null check (char_length(senha) between 6 and 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create table if not exists public.paises (
	codpais integer generated by default as identity primary key,
	pais varchar(60) not null check (char_length(pais) between 2 and 60),
	sigla varchar(5) check (sigla is null or char_length(sigla) <= 5),
	ddi varchar(5) check (ddi is null or char_length(ddi) <= 5),
	moeda varchar(10) check (moeda is null or char_length(moeda) <= 10),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create table if not exists public.estados (
	codestado integer generated by default as identity primary key,
	uf char(2) not null check (char_length(uf) = 2),
	estado varchar(60) not null check (char_length(estado) between 2 and 60),
	codpais integer not null references public.paises(codpais),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create table if not exists public.cidades (
	codcidade integer generated by default as identity primary key,
	cidade varchar(100) not null check (char_length(cidade) between 2 and 100),
	codest integer not null references public.estados(codestado),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create table if not exists public.condicoes_pagamento (
	codcondicao_pagamento integer generated by default as identity primary key,
	nome varchar(80) not null check (char_length(nome) between 2 and 80),
	prazo_dias integer not null default 0 check (prazo_dias >= 0),
	parcelas integer not null default 1 check (parcelas >= 1),
	juro numeric not null default 0 check (juro >= 0),
	multa numeric not null default 0 check (multa >= 0),
	desconto numeric not null default 0 check (desconto >= 0),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create table if not exists public.categorias (
	codcategoria integer generated by default as identity primary key,
	nome varchar(80) not null unique check (char_length(nome) between 2 and 80),
	descricao text,
	tipo varchar(20) not null default 'AMBOS' check (tipo in ('PRODUTO', 'SERVICO', 'AMBOS')),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create table if not exists public.produtos (
	codproduto integer generated by default as identity primary key,
	nome varchar(150) not null check (char_length(nome) between 2 and 150),
	codcategoria integer references public.categorias(codcategoria),
	valor numeric not null default 0 check (valor >= 0),
	quantidade_estoque integer not null default 0 check (quantidade_estoque >= 0),
	valor_desconto numeric default 0 check (valor_desconto >= 0),
	descricao text,
	imagem_url text,
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario),
	check (valor_desconto <= valor)
);

create table if not exists public.servicos (
	codservico integer generated by default as identity primary key,
	nome varchar(150) not null check (char_length(nome) between 2 and 150),
	codcategoria integer references public.categorias(codcategoria),
	duracao_minutos integer not null check (duracao_minutos > 0),
	valor numeric not null default 0 check (valor >= 0),
	valor_desconto numeric default 0 check (valor_desconto >= 0),
	descricao text,
	imagem_url text,
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario),
	check (valor_desconto <= valor)
);

create table if not exists public.clientes (
	codcliente bigint generated by default as identity primary key,
	tipo text not null check (tipo in ('FISICA', 'JURIDICA')),
	cliente text not null check (char_length(cliente) between 5 and 60),
	apelido text check (apelido is null or char_length(apelido) <= 60),
	estado_civil text check (
		estado_civil is null
		or estado_civil in ('SOLTEIRO', 'CASADO', 'SEPARADO', 'DIVORCIADO', 'VIUVO', 'OUTRO')
	),
	endereco text not null check (char_length(endereco) between 5 and 60),
	numero text not null check (char_length(numero) between 1 and 10),
	complemento text check (complemento is null or char_length(complemento) <= 60),
	bairro text not null check (char_length(bairro) between 5 and 60),
	cep text not null check (char_length(cep) between 8 and 9),
	codcidade integer not null references public.cidades(codcidade),
	codcondicao_pagamento integer references public.condicoes_pagamento(codcondicao_pagamento),
	telefone text not null check (char_length(telefone) between 5 and 20),
	email text not null check (char_length(email) between 5 and 60),
	sexo text check (sexo is null or sexo in ('MASCULINO', 'FEMININO', 'OUTROS')),
	nacionalidade text check (nacionalidade is null or char_length(nacionalidade) between 5 and 20),
	data_nascimento date,
	rg_inscricao_estadual text check (
		rg_inscricao_estadual is null or char_length(rg_inscricao_estadual) between 5 and 14
	),
	cpf_cnpj text check (cpf_cnpj is null or char_length(cpf_cnpj) between 5 and 14),
	observacoes text check (observacoes is null or char_length(observacoes) <= 255),
	data_criacao timestamptz not null default now(),
	data_atualizacao timestamptz not null default now(),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N'))
);

drop trigger if exists set_usuarios_data_ult_alteracao on public.usuarios;
create trigger set_usuarios_data_ult_alteracao
before update on public.usuarios
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_paises_data_ult_alteracao on public.paises;
create trigger set_paises_data_ult_alteracao
before update on public.paises
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_estados_data_ult_alteracao on public.estados;
create trigger set_estados_data_ult_alteracao
before update on public.estados
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_cidades_data_ult_alteracao on public.cidades;
create trigger set_cidades_data_ult_alteracao
before update on public.cidades
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_condicoes_pagamento_data_ult_alteracao on public.condicoes_pagamento;
create trigger set_condicoes_pagamento_data_ult_alteracao
before update on public.condicoes_pagamento
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_categorias_data_ult_alteracao on public.categorias;
create trigger set_categorias_data_ult_alteracao
before update on public.categorias
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_produtos_data_ult_alteracao on public.produtos;
create trigger set_produtos_data_ult_alteracao
before update on public.produtos
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_servicos_data_ult_alteracao on public.servicos;
create trigger set_servicos_data_ult_alteracao
before update on public.servicos
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_clientes_data_atualizacao on public.clientes;
create trigger set_clientes_data_atualizacao
before update on public.clientes
for each row execute function public.set_data_atualizacao();
