begin;

create schema if not exists public;

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

create or replace function public.set_data_atualizacao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_atualizacao = now();
	return new;
end;
$$;

create table if not exists public.usuarios (
	codusuario integer generated by default as identity primary key,
	usuario varchar(50) not null unique check (char_length(usuario) between 3 and 50),
	senha varchar(255) not null check (char_length(senha) between 6 and 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create table if not exists public.paises (
	codpais integer generated by default as identity primary key,
	pais varchar(56) not null check (char_length(pais) between 2 and 56),
	sigla varchar(5) check (sigla is null or char_length(sigla) <= 5),
	ddi varchar(5) check (ddi is null or char_length(ddi) <= 5),
	moeda varchar(10) check (moeda is null or char_length(moeda) <= 10),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

alter table public.paises
	drop constraint if exists paises_pais_check;

alter table public.paises
	alter column pais type varchar(56);

alter table public.paises
	add constraint paises_pais_check
	check (char_length(pais) between 2 and 56);

create table if not exists public.estados (
	codestado integer generated by default as identity primary key,
	uf char(2) not null check (char_length(uf) = 2),
	estado varchar(50) not null check (char_length(estado) between 2 and 50),
	codpais integer not null references public.paises(codpais),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

alter table public.estados
	drop constraint if exists estados_estado_check;

alter table public.estados
	alter column estado type varchar(50);

alter table public.estados
	add constraint estados_estado_check
	check (char_length(estado) between 2 and 50);

create table if not exists public.cidades (
	codcidade integer generated by default as identity primary key,
	cidade varchar(50) not null check (char_length(cidade) between 2 and 50),
	codest integer not null references public.estados(codestado),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

alter table public.cidades
	drop constraint if exists cidades_cidade_check;

alter table public.cidades
	alter column cidade type varchar(50);

alter table public.cidades
	add constraint cidades_cidade_check
	check (char_length(cidade) between 2 and 50);

create table if not exists public.condicoes_pagamento (
	codcondicao_pagamento integer generated by default as identity primary key,
	condicao_pagamento varchar(50) not null check (char_length(condicao_pagamento) between 2 and 50),
	codforma_pagamento integer,
	prazo_dias integer not null default 0 check (prazo_dias >= 0),
	parcelas integer not null default 1 check (parcelas >= 1),
	juro numeric not null default 0 check (juro >= 0),
	multa numeric not null default 0 check (multa >= 0),
	desconto numeric not null default 0 check (desconto >= 0),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'condicoes_pagamento'
			and column_name = 'nome'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'condicoes_pagamento'
			and column_name = 'condicao_pagamento'
	) then
		alter table public.condicoes_pagamento rename column nome to condicao_pagamento;
	end if;
end $$;

alter table public.condicoes_pagamento
	drop constraint if exists condicoes_pagamento_nome_check;

alter table public.condicoes_pagamento
	drop constraint if exists condicoes_pagamento_condicao_pagamento_check;

alter table public.condicoes_pagamento
	alter column condicao_pagamento type varchar(50);

alter table public.condicoes_pagamento
	add constraint condicoes_pagamento_condicao_pagamento_check
	check (char_length(condicao_pagamento) between 2 and 50);

create table if not exists public.formas_pagamento (
	codforma_pagamento integer generated by default as identity primary key,
	forma_pagamento varchar(50) not null unique check (char_length(forma_pagamento) between 2 and 50),
	tipo varchar(20) not null default 'OUTROS' check (
		tipo in ('DINHEIRO', 'PIX', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'BOLETO', 'TRANSFERENCIA', 'OUTROS')
	),
	descricao text check (descricao is null or char_length(descricao) <= 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

alter table public.formas_pagamento
	drop constraint if exists formas_pagamento_forma_pagamento_check;

alter table public.formas_pagamento
	alter column forma_pagamento type varchar(50);

alter table public.formas_pagamento
	add constraint formas_pagamento_forma_pagamento_check
	check (char_length(forma_pagamento) between 2 and 50);

alter table public.condicoes_pagamento
	drop constraint if exists condicoes_pagamento_codforma_pagamento_fkey;

alter table public.condicoes_pagamento
	add constraint condicoes_pagamento_codforma_pagamento_fkey
	foreign key (codforma_pagamento) references public.formas_pagamento(codforma_pagamento);

create table if not exists public.condicoes_pagamento_parcelas (
	codcondicao_pagamento integer not null,
	num_parcela integer not null check (num_parcela >= 1),
	dias_vencimento integer not null check (dias_vencimento >= 0),
	codforma_pagamento integer not null,
	percentual numeric(7,4) not null check (percentual > 0 and percentual <= 100),
	constraint condicoes_pagamento_parcelas_pkey
		primary key (codcondicao_pagamento, num_parcela),
	constraint condicoes_pagamento_parcelas_condicao_fkey
		foreign key (codcondicao_pagamento)
		references public.condicoes_pagamento(codcondicao_pagamento)
		on delete cascade,
	constraint condicoes_pagamento_parcelas_forma_fkey
		foreign key (codforma_pagamento)
		references public.formas_pagamento(codforma_pagamento)
);

create index if not exists condicoes_pagamento_parcelas_forma_idx
	on public.condicoes_pagamento_parcelas (codforma_pagamento);

insert into public.condicoes_pagamento_parcelas (
	codcondicao_pagamento,
	num_parcela,
	dias_vencimento,
	codforma_pagamento,
	percentual
)
select
	cp.codcondicao_pagamento,
	parcela.num_parcela,
	cp.prazo_dias * parcela.num_parcela,
	cp.codforma_pagamento,
	case
		when parcela.num_parcela = cp.parcelas
			then 100 - round(100.0 / cp.parcelas, 4) * (cp.parcelas - 1)
		else round(100.0 / cp.parcelas, 4)
	end
from public.condicoes_pagamento cp
cross join lateral generate_series(1, cp.parcelas) as parcela(num_parcela)
where cp.codforma_pagamento is not null
on conflict (codcondicao_pagamento, num_parcela) do nothing;

create table if not exists public.categorias (
	codcategoria integer generated by default as identity primary key,
	categoria varchar(50) not null unique check (char_length(categoria) between 2 and 50),
	descricao text check (descricao is null or char_length(descricao) <= 255),
	tipo varchar(20) not null default 'AMBOS' check (tipo in ('PRODUTO', 'SERVICO', 'AMBOS')),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'categorias'
			and column_name = 'nome'
	)
	and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'categorias'
			and column_name = 'categoria'
	) then
		alter table public.categorias rename column nome to categoria;
	end if;
end $$;

alter table public.categorias
	drop constraint if exists categorias_nome_check;

alter table public.categorias
	drop constraint if exists categorias_categoria_check;

alter table public.categorias
	alter column categoria type varchar(50);

alter table public.categorias
	add constraint categorias_categoria_check
	check (char_length(categoria) between 2 and 50);

create table if not exists public.marcas (
	codmarca integer generated by default as identity primary key,
	marca varchar(40) not null unique check (char_length(marca) between 2 and 40),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

alter table public.marcas
	drop constraint if exists marcas_marca_check;

alter table public.marcas
	alter column marca type varchar(40);

alter table public.marcas
	add constraint marcas_marca_check
	check (char_length(marca) between 2 and 40);

alter table public.marcas
	drop constraint if exists marcas_descricao_check;

alter table public.marcas
	drop column if exists descricao;

create table if not exists public.unidades_medida (
	codunidade_medida integer generated by default as identity primary key,
	unidade_medida varchar(40) not null unique check (char_length(unidade_medida) between 2 and 40),
	sigla varchar(10) not null unique check (char_length(sigla) between 1 and 10),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

alter table public.unidades_medida
	drop constraint if exists unidades_medida_unidade_medida_check;

alter table public.unidades_medida
	alter column unidade_medida type varchar(40);

alter table public.unidades_medida
	add constraint unidades_medida_unidade_medida_check
	check (char_length(unidade_medida) between 2 and 40);

alter table public.unidades_medida
	drop constraint if exists unidades_medida_descricao_check;

alter table public.unidades_medida
	drop column if exists descricao;

create table if not exists public.produtos (
	codproduto integer generated by default as identity primary key,
	produto varchar(40) not null check (char_length(produto) between 2 and 40),
	codcategoria integer references public.categorias(codcategoria),
	codmarca integer references public.marcas(codmarca),
	codunidade_medida integer references public.unidades_medida(codunidade_medida),
	valor numeric not null default 0 check (valor >= 0),
	quantidade_estoque integer not null default 0 check (quantidade_estoque >= 0),
	valor_desconto numeric default 0 check (valor_desconto >= 0),
	imagem_url text,
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario),
	check (valor_desconto <= valor)
);

alter table public.produtos
	drop constraint if exists produtos_produto_check;

alter table public.produtos
	alter column produto type varchar(40);

alter table public.produtos
	add constraint produtos_produto_check
	check (char_length(produto) between 2 and 40);

alter table public.produtos
	drop constraint if exists produtos_descricao_check;

alter table public.produtos
	drop column if exists descricao;

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'produtos'
			and column_name = 'nome'
	)
	and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'produtos'
			and column_name = 'produto'
	) then
		alter table public.produtos rename column nome to produto;
	end if;
end $$;

create table if not exists public.servicos (
	codservico integer generated by default as identity primary key,
	servico varchar(50) not null check (char_length(servico) between 2 and 50),
	codcategoria integer references public.categorias(codcategoria),
	duracao_minutos integer not null check (duracao_minutos > 0),
	valor numeric not null default 0 check (valor >= 0),
	valor_desconto numeric default 0 check (valor_desconto >= 0),
	imagem_url text,
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario),
	check (valor_desconto <= valor)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'servicos'
			and column_name = 'nome'
	)
	and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'servicos'
			and column_name = 'servico'
	) then
		alter table public.servicos rename column nome to servico;
	end if;
end $$;

alter table public.servicos
	drop constraint if exists servicos_nome_check;

alter table public.servicos
	drop constraint if exists servicos_servico_check;

alter table public.servicos
	alter column servico type varchar(50);

alter table public.servicos
	add constraint servicos_servico_check
	check (char_length(servico) between 2 and 50);

alter table public.servicos
	drop constraint if exists servicos_descricao_check;

alter table public.servicos
	drop column if exists descricao;

create table if not exists public.clientes (
	codcliente bigint generated by default as identity primary key,
	tipo text not null check (tipo in ('FISICA', 'JURIDICA')),
	cliente text not null check (char_length(cliente) between 5 and 60),
	apelido text check (apelido is null or char_length(apelido) <= 60),
	estado_civil text check (
		estado_civil is null
		or estado_civil in ('SOLTEIRO', 'CASADO', 'SEPARADO', 'DIVORCIADO', 'VIUVO', 'OUTRO')
	),
	endereco text not null check (char_length(endereco) between 5 and 60),
	numero text not null check (char_length(numero) between 1 and 10),
	complemento text check (complemento is null or char_length(complemento) <= 60),
	bairro text not null check (char_length(bairro) between 5 and 60),
	cep text not null check (char_length(cep) = 8),
	codcidade integer not null references public.cidades(codcidade),
	codcondicao_pagamento integer references public.condicoes_pagamento(codcondicao_pagamento),
	telefone text not null check (char_length(telefone) in (10, 11)),
	contato text check (contato is null or char_length(contato) <= 60),
	email text not null check (char_length(email) between 5 and 60),
	sexo text check (sexo is null or sexo in ('MASCULINO', 'FEMININO', 'OUTROS')),
	nacionalidade text check (nacionalidade is null or char_length(nacionalidade) between 5 and 20),
	data_nascimento date,
	rg_inscricao_estadual text check (
		rg_inscricao_estadual is null or char_length(rg_inscricao_estadual) between 5 and 14
	),
	cpf_cnpj text check (cpf_cnpj is null or char_length(cpf_cnpj) in (11, 14)),
	observacoes text check (observacoes is null or char_length(observacoes) <= 110),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create table if not exists public.fornecedores (
	codfornecedor bigint generated by default as identity primary key,
	tipo text not null check (tipo in ('FISICA', 'JURIDICA')),
	fornecedor text not null check (char_length(fornecedor) between 5 and 80),
	nome_fantasia text check (nome_fantasia is null or char_length(nome_fantasia) <= 80),
	contato text check (contato is null or char_length(contato) <= 60),
	endereco text not null check (char_length(endereco) between 5 and 80),
	numero text not null check (char_length(numero) between 1 and 10),
	complemento text check (complemento is null or char_length(complemento) <= 60),
	bairro text not null check (char_length(bairro) between 5 and 60),
	cep text not null check (char_length(cep) = 8),
	codcidade integer not null references public.cidades(codcidade),
	codcondicao_pagamento integer,
	telefone text not null check (char_length(telefone) in (10, 11)),
	email text not null check (char_length(email) between 5 and 80),
	rg_inscricao_estadual text check (
		rg_inscricao_estadual is null or char_length(rg_inscricao_estadual) between 5 and 14
	),
	cpf_cnpj text check (cpf_cnpj is null or char_length(cpf_cnpj) in (11, 14)),
	observacoes text check (observacoes is null or char_length(observacoes) <= 110),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create table if not exists public.funcoes_funcionarios (
	codfuncao_funcionario integer generated by default as identity primary key,
	funcao_funcionario varchar(60) not null unique check (char_length(funcao_funcionario) between 2 and 60),
	descricao text check (descricao is null or char_length(descricao) <= 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create table if not exists public.funcionarios (
	codfuncionario integer generated by default as identity primary key,
	funcionario varchar(60) not null check (char_length(funcionario) between 5 and 60),
	apelido varchar(35) check (apelido is null or char_length(apelido) <= 35),
	estado_civil text check (
		estado_civil is null
		or estado_civil in ('SOLTEIRO', 'CASADO', 'SEPARADO', 'DIVORCIADO', 'VIUVO', 'OUTRO')
	),
	endereco text check (endereco is null or char_length(endereco) between 5 and 80),
	numero text check (numero is null or char_length(numero) between 1 and 10),
	complemento text check (complemento is null or char_length(complemento) <= 60),
	bairro text check (bairro is null or char_length(bairro) between 5 and 60),
	cep text check (cep is null or char_length(cep) = 8),
	codcidade integer references public.cidades(codcidade),
	codfuncao_funcionario integer not null references public.funcoes_funcionarios(codfuncao_funcionario),
	telefone varchar(11) not null check (char_length(telefone) in (10, 11)),
	contato varchar(60) check (contato is null or char_length(contato) <= 60),
	email varchar(80) check (email is null or char_length(email) between 5 and 80),
	sexo text check (sexo is null or sexo in ('MASCULINO', 'FEMININO')),
	nacionalidade text check (nacionalidade is null or char_length(nacionalidade) between 5 and 20),
	cpf varchar(11) not null unique check (char_length(cpf) = 11),
	rg varchar(14) check (rg is null or char_length(rg) between 5 and 14),
	data_nascimento date,
	data_admissao date not null default current_date,
	data_demissao date,
	salario_base numeric not null default 0 check (salario_base >= 0),
	percentual_comissao numeric not null default 0 check (percentual_comissao between 0 and 100),
	observacoes text check (observacoes is null or char_length(observacoes) <= 110),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

alter table public.funcionarios
	drop constraint if exists funcionarios_funcionario_check;

alter table public.funcionarios
	drop constraint if exists funcionarios_apelido_check;

alter table public.funcionarios
	alter column funcionario type varchar(60),
	alter column apelido type varchar(35);

alter table public.funcionarios
	add constraint funcionarios_funcionario_check
	check (char_length(funcionario) between 5 and 60);

alter table public.funcionarios
	add constraint funcionarios_apelido_check
	check (apelido is null or char_length(apelido) <= 35);

alter table public.funcionarios
add column if not exists data_demissao date;

alter table public.funcionarios
add column if not exists estado_civil text check (
	estado_civil is null
	or estado_civil in ('SOLTEIRO', 'CASADO', 'SEPARADO', 'DIVORCIADO', 'VIUVO', 'OUTRO')
);

alter table public.funcionarios
add column if not exists endereco text check (endereco is null or char_length(endereco) between 5 and 80);

alter table public.funcionarios
add column if not exists numero text check (numero is null or char_length(numero) between 1 and 10);

alter table public.funcionarios
add column if not exists complemento text check (complemento is null or char_length(complemento) <= 60);

alter table public.funcionarios
add column if not exists bairro text check (bairro is null or char_length(bairro) between 5 and 60);

alter table public.funcionarios
add column if not exists cep text check (cep is null or char_length(cep) = 8);

alter table public.funcionarios
add column if not exists codcidade integer references public.cidades(codcidade);

alter table public.funcionarios
add column if not exists sexo text check (sexo is null or sexo in ('MASCULINO', 'FEMININO'));

alter table public.funcionarios
add column if not exists nacionalidade text check (nacionalidade is null or char_length(nacionalidade) between 5 and 20);

alter table public.clientes
add column if not exists contato text check (contato is null or char_length(contato) <= 60);

alter table public.funcionarios
add column if not exists contato varchar(60) check (contato is null or char_length(contato) <= 60);

create table if not exists public.contas_pagar (
	codconta_pagar bigint generated by default as identity primary key,
	conta_pagar varchar(120) not null check (char_length(conta_pagar) between 2 and 120),
	codfornecedor bigint not null references public.fornecedores(codfornecedor),
	codforma_pagamento integer references public.formas_pagamento(codforma_pagamento),
	numero_documento varchar(60) check (numero_documento is null or char_length(numero_documento) <= 60),
	data_emissao date not null default current_date,
	data_vencimento date not null,
	data_pagamento date,
	valor numeric not null check (valor > 0),
	valor_pago numeric not null default 0 check (valor_pago >= 0),
	status varchar(20) not null default 'PENDENTE' check (status in ('PENDENTE', 'PAGO', 'CANCELADO')),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	observacoes text check (observacoes is null or char_length(observacoes) <= 110),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario),
	check (valor_pago <= valor)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'nome'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'fornecedor'
	) then
		alter table public.fornecedores rename column nome to fornecedor;
	end if;

	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'descricao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'conta_pagar'
	) then
		alter table public.contas_pagar rename column descricao to conta_pagar;
	end if;
end $$;

alter table public.contas_pagar
add column if not exists ativo char(1) not null default 'S' check (ativo in ('S', 'N'));

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'clientes'
			and column_name = 'data_criacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'clientes'
			and column_name = 'data_cadastro'
	) then
		alter table public.clientes rename column data_criacao to data_cadastro;
	end if;

	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'clientes'
			and column_name = 'data_atualizacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'clientes'
			and column_name = 'data_ult_alteracao'
	) then
		alter table public.clientes rename column data_atualizacao to data_ult_alteracao;
	end if;
end $$;

alter table public.clientes
add column if not exists data_cadastro timestamp not null default current_timestamp;

alter table public.clientes
add column if not exists data_ult_alteracao timestamp not null default current_timestamp;

alter table public.clientes
add column if not exists usuario_ult_alteracao integer references public.usuarios(codusuario);

alter table public.clientes
alter column data_cadastro type timestamp using data_cadastro::timestamp,
alter column data_cadastro set default current_timestamp,
alter column data_cadastro set not null,
alter column data_ult_alteracao type timestamp using data_ult_alteracao::timestamp,
alter column data_ult_alteracao set default current_timestamp,
alter column data_ult_alteracao set not null;

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'data_criacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'data_cadastro'
	) then
		alter table public.fornecedores rename column data_criacao to data_cadastro;
	end if;

	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'data_atualizacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'data_ult_alteracao'
	) then
		alter table public.fornecedores rename column data_atualizacao to data_ult_alteracao;
	end if;
end $$;

alter table public.fornecedores
add column if not exists data_cadastro timestamp not null default current_timestamp;

alter table public.fornecedores
add column if not exists data_ult_alteracao timestamp not null default current_timestamp;

alter table public.fornecedores
add column if not exists usuario_ult_alteracao integer references public.usuarios(codusuario);

alter table public.fornecedores
add column if not exists codcondicao_pagamento integer;

alter table public.fornecedores
drop constraint if exists fk_fornecedores_condicoes_pagamento;

alter table public.fornecedores
add constraint fk_fornecedores_condicoes_pagamento
foreign key (codcondicao_pagamento)
references public.condicoes_pagamento(codcondicao_pagamento);

alter table public.fornecedores
alter column data_cadastro type timestamp using data_cadastro::timestamp,
alter column data_cadastro set default current_timestamp,
alter column data_cadastro set not null,
alter column data_ult_alteracao type timestamp using data_ult_alteracao::timestamp,
alter column data_ult_alteracao set default current_timestamp,
alter column data_ult_alteracao set not null;

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'data_criacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'data_cadastro'
	) then
		alter table public.contas_pagar rename column data_criacao to data_cadastro;
	end if;

	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'data_atualizacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'data_ult_alteracao'
	) then
		alter table public.contas_pagar rename column data_atualizacao to data_ult_alteracao;
	end if;
end $$;

alter table public.contas_pagar
add column if not exists data_cadastro timestamp not null default current_timestamp;

alter table public.contas_pagar
add column if not exists data_ult_alteracao timestamp not null default current_timestamp;

alter table public.contas_pagar
add column if not exists usuario_ult_alteracao integer references public.usuarios(codusuario);

alter table public.contas_pagar
alter column data_cadastro type timestamp using data_cadastro::timestamp,
alter column data_cadastro set default current_timestamp,
alter column data_cadastro set not null,
alter column data_ult_alteracao type timestamp using data_ult_alteracao::timestamp,
alter column data_ult_alteracao set default current_timestamp,
alter column data_ult_alteracao set not null;

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'funcionarios'
			and column_name = 'cargo'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'funcionarios'
			and column_name = 'codfuncao_funcionario'
	) then
		insert into public.funcoes_funcionarios (funcao_funcionario)
		select distinct trim(cargo)
		from public.funcionarios
		where cargo is not null
			and trim(cargo) <> ''
		on conflict (funcao_funcionario) do nothing;

		alter table public.funcionarios
		add column codfuncao_funcionario integer references public.funcoes_funcionarios(codfuncao_funcionario);

		update public.funcionarios f
		set codfuncao_funcionario = ff.codfuncao_funcionario
		from public.funcoes_funcionarios ff
		where ff.funcao_funcionario = trim(f.cargo);

		alter table public.funcionarios
		alter column codfuncao_funcionario set not null;

		alter table public.funcionarios
		drop column cargo;
	end if;
end $$;

create index if not exists idx_contas_pagar_fornecedor
on public.contas_pagar(codfornecedor);

create index if not exists idx_contas_pagar_vencimento
on public.contas_pagar(data_vencimento);

drop trigger if exists set_usuarios_data_ult_alteracao on public.usuarios;
create trigger set_usuarios_data_ult_alteracao
before update on public.usuarios
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_paises_data_ult_alteracao on public.paises;
create trigger set_paises_data_ult_alteracao
before update on public.paises
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_estados_data_ult_alteracao on public.estados;
create trigger set_estados_data_ult_alteracao
before update on public.estados
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_cidades_data_ult_alteracao on public.cidades;
create trigger set_cidades_data_ult_alteracao
before update on public.cidades
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_condicoes_pagamento_data_ult_alteracao on public.condicoes_pagamento;
create trigger set_condicoes_pagamento_data_ult_alteracao
before update on public.condicoes_pagamento
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_formas_pagamento_data_ult_alteracao on public.formas_pagamento;
create trigger set_formas_pagamento_data_ult_alteracao
before update on public.formas_pagamento
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_categorias_data_ult_alteracao on public.categorias;
create trigger set_categorias_data_ult_alteracao
before update on public.categorias
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_marcas_data_ult_alteracao on public.marcas;
create trigger set_marcas_data_ult_alteracao
before update on public.marcas
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_unidades_medida_data_ult_alteracao on public.unidades_medida;
create trigger set_unidades_medida_data_ult_alteracao
before update on public.unidades_medida
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_produtos_data_ult_alteracao on public.produtos;
create trigger set_produtos_data_ult_alteracao
before update on public.produtos
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_servicos_data_ult_alteracao on public.servicos;
create trigger set_servicos_data_ult_alteracao
before update on public.servicos
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_clientes_data_atualizacao on public.clientes;
drop trigger if exists set_clientes_data_ult_alteracao on public.clientes;
create trigger set_clientes_data_ult_alteracao
before update on public.clientes
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_fornecedores_data_atualizacao on public.fornecedores;
drop trigger if exists set_fornecedores_data_ult_alteracao on public.fornecedores;
create trigger set_fornecedores_data_ult_alteracao
before update on public.fornecedores
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_funcoes_funcionarios_data_ult_alteracao on public.funcoes_funcionarios;
create trigger set_funcoes_funcionarios_data_ult_alteracao
before update on public.funcoes_funcionarios
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_funcionarios_data_ult_alteracao on public.funcionarios;
create trigger set_funcionarios_data_ult_alteracao
before update on public.funcionarios
for each row execute function public.set_data_ult_alteracao();

drop trigger if exists set_contas_pagar_data_atualizacao on public.contas_pagar;
drop trigger if exists set_contas_pagar_data_ult_alteracao on public.contas_pagar;
create trigger set_contas_pagar_data_ult_alteracao
before update on public.contas_pagar
for each row execute function public.set_data_ult_alteracao();

-- Dados atuais

-- public.usuarios
-- sem registros em public.usuarios

-- public.paises
insert into public."paises" ("codpais", "pais", "sigla", "ddi", "moeda", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (1, 'Brasil', 'BR', '55', 'BRL', 'S', '2026-04-11 21:07:45.389', '2026-04-11 21:07:45.389', NULL);

-- public.estados
insert into public."estados" ("codestado", "uf", "estado", "codpais", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (1, 'PR', 'Paraná', 1, 'S', '2026-05-06 02:58:19.427', '2026-05-06 02:58:19.427', NULL);
insert into public."estados" ("codestado", "uf", "estado", "codpais", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (2, 'SP', 'São Paulo', 1, 'S', '2026-05-28 23:06:42.019', '2026-05-28 23:06:42.019', NULL);

-- public.cidades
insert into public."cidades" ("codcidade", "cidade", "codest", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (1, 'Foz do Iguaçu', 1, 'S', '2026-05-06 02:58:35.455', '2026-05-06 02:58:35.455', NULL);

-- public.formas_pagamento
insert into public."formas_pagamento" ("codforma_pagamento", "forma_pagamento", "tipo", "descricao", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (2, 'PIX', 'PIX', 'Forma de pagamento PIX.', 'S', '2026-05-27 01:07:27.768', '2026-05-27 01:07:27.768', NULL);
insert into public."formas_pagamento" ("codforma_pagamento", "forma_pagamento", "tipo", "descricao", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (3, 'Cartão de Crédito', 'CARTAO_CREDITO', 'Forma de pagamento no cartão de crédito.', 'S', '2026-05-30 00:45:28.546', '2026-05-30 00:45:28.546', NULL);
insert into public."formas_pagamento" ("codforma_pagamento", "forma_pagamento", "tipo", "descricao", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (4, 'Cartão de Débito', 'CARTAO_DEBITO', 'Forma de pagamento no débito.', 'S', '2026-05-30 18:12:20.808', '2026-05-30 18:12:20.808', NULL);

-- public.condicoes_pagamento
insert into public."condicoes_pagamento" ("codcondicao_pagamento", "condicao_pagamento", "prazo_dias", "parcelas", "juro", "multa", "desconto", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao", "codforma_pagamento") values (4, 'À vista', 0, 1, '0', '0', '0', 'S', '2026-05-30 18:06:37.766', '2026-05-30 18:06:37.766', NULL, 2);

insert into public.condicoes_pagamento_parcelas (
	codcondicao_pagamento,
	num_parcela,
	dias_vencimento,
	codforma_pagamento,
	percentual
)
select
	cp.codcondicao_pagamento,
	parcela.num_parcela,
	cp.prazo_dias * parcela.num_parcela,
	cp.codforma_pagamento,
	case
		when parcela.num_parcela = cp.parcelas
			then 100 - round(100.0 / cp.parcelas, 4) * (cp.parcelas - 1)
		else round(100.0 / cp.parcelas, 4)
	end
from public.condicoes_pagamento cp
cross join lateral generate_series(1, cp.parcelas) as parcela(num_parcela)
where cp.codforma_pagamento is not null
on conflict (codcondicao_pagamento, num_parcela) do nothing;

-- public.categorias
insert into public."categorias" ("codcategoria", "categoria", "descricao", "tipo", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (1, 'Finalização', 'Produtos e serviços utilizados para modelar, fixar e dar acabamento ao cabelo após o corte, garantindo estilo e durabilidade do penteado.', 'PRODUTO', 'S', '2026-04-11 22:05:39.203', '2026-04-11 22:05:39.203', NULL);
insert into public."categorias" ("codcategoria", "categoria", "descricao", "tipo", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (2, 'Cabelo', 'Serviços relacionados ao cabelo.', 'SERVICO', 'S', '2026-05-16 19:20:00.872', '2026-05-16 19:20:00.872', NULL);

-- public.marcas
insert into public."marcas" ("codmarca", "marca", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (3, 'Don Alcides', 'S', '2026-05-27 01:06:25.280', '2026-05-27 01:06:25.280', NULL);

-- public.unidades_medida
insert into public."unidades_medida" ("codunidade_medida", "unidade_medida", "sigla", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (1, 'Unidade', 'UN', 'S', '2026-05-30 17:50:54.996', '2026-05-30 17:50:54.996', NULL);
insert into public."unidades_medida" ("codunidade_medida", "unidade_medida", "sigla", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (2, 'Mililitro', 'ML', 'S', '2026-05-30 17:50:54.996', '2026-05-30 17:50:54.996', NULL);
insert into public."unidades_medida" ("codunidade_medida", "unidade_medida", "sigla", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (3, 'Grama', 'G', 'S', '2026-05-30 17:50:54.996', '2026-05-30 17:50:54.996', NULL);

-- public.produtos
insert into public."produtos" ("codproduto", "produto", "codcategoria", "valor", "quantidade_estoque", "valor_desconto", "imagem_url", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao", "codmarca", "codunidade_medida") values (3, 'Corte Social', NULL, '10828', 50, '8', NULL, 'S', '2026-05-20 00:14:43.795', '2026-05-30 18:08:20.670', NULL, NULL, 1);
insert into public."produtos" ("codproduto", "produto", "codcategoria", "valor", "quantidade_estoque", "valor_desconto", "imagem_url", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao", "codmarca", "codunidade_medida") values (2, 'Pomada Modeladora', 1, '399', 40, '12', 'https://lbiuoahiddvhryxtqdgy.supabase.co/storage/v1/object/public/upload/produtos/1776984543035-foto-teia-11.png', 'S', '2026-04-24 01:49:02.459', '2026-05-30 18:08:45.967', NULL, NULL, 3);

-- public.servicos
insert into public."servicos" ("codservico", "servico", "codcategoria", "duracao_minutos", "valor", "valor_desconto", "imagem_url", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (1, 'Corte Social', 2, 30, '35.5', '5', NULL, 'S', '2026-05-16 19:20:40.927', '2026-05-16 19:20:40.927', NULL);

-- public.clientes
insert into public."clientes" ("codcliente", "tipo", "cliente", "apelido", "estado_civil", "endereco", "numero", "complemento", "bairro", "cep", "codcidade", "codcondicao_pagamento", "telefone", "email", "sexo", "nacionalidade", "data_nascimento", "rg_inscricao_estadual", "cpf_cnpj", "observacoes", "data_cadastro", "data_ult_alteracao", "ativo", "usuario_ult_alteracao", "contato") values ('5', 'FISICA', 'Bruno Fontana', 'Bruno', 'SOLTEIRO', 'Avenida Parati', '1521', 'Cond. Moradas da Vila', 'Vila A', '85860450', 1, 4, '45999057378', 'brunofontana895@gmail.com', 'MASCULINO', 'Brasileiro', '2005-05-27 03:00:00.000', '123456789', '01374606944', 'teste de observacao aaa', '2026-05-20 00:56:32.854', '2026-05-30 18:06:53.230', 'S', NULL, NULL);

-- public.fornecedores
-- sem registros em public.fornecedores

-- public.funcoes_funcionarios
insert into public."funcoes_funcionarios" ("codfuncao_funcionario", "funcao_funcionario", "descricao", "ativo", "data_cadastro", "data_ult_alteracao", "usuario_ult_alteracao") values (1, 'Barbeiro', 'Teste descrição.', 'S', '2026-05-30 16:59:09.939', '2026-05-30 16:59:09.939', NULL);

-- public.funcionarios
-- sem registros em public.funcionarios

-- public.contas_pagar
-- sem registros em public.contas_pagar

-- Ajuste das sequences/identity apos inserir IDs explicitos
select setval(pg_get_serial_sequence('public.usuarios', 'codusuario'), coalesce((select max("codusuario") from public."usuarios"), 1), exists(select 1 from public."usuarios"));
select setval(pg_get_serial_sequence('public.paises', 'codpais'), coalesce((select max("codpais") from public."paises"), 1), exists(select 1 from public."paises"));
select setval(pg_get_serial_sequence('public.estados', 'codestado'), coalesce((select max("codestado") from public."estados"), 1), exists(select 1 from public."estados"));
select setval(pg_get_serial_sequence('public.cidades', 'codcidade'), coalesce((select max("codcidade") from public."cidades"), 1), exists(select 1 from public."cidades"));
select setval(pg_get_serial_sequence('public.formas_pagamento', 'codforma_pagamento'), coalesce((select max("codforma_pagamento") from public."formas_pagamento"), 1), exists(select 1 from public."formas_pagamento"));
select setval(pg_get_serial_sequence('public.condicoes_pagamento', 'codcondicao_pagamento'), coalesce((select max("codcondicao_pagamento") from public."condicoes_pagamento"), 1), exists(select 1 from public."condicoes_pagamento"));
select setval(pg_get_serial_sequence('public.categorias', 'codcategoria'), coalesce((select max("codcategoria") from public."categorias"), 1), exists(select 1 from public."categorias"));
select setval(pg_get_serial_sequence('public.marcas', 'codmarca'), coalesce((select max("codmarca") from public."marcas"), 1), exists(select 1 from public."marcas"));
select setval(pg_get_serial_sequence('public.unidades_medida', 'codunidade_medida'), coalesce((select max("codunidade_medida") from public."unidades_medida"), 1), exists(select 1 from public."unidades_medida"));
select setval(pg_get_serial_sequence('public.produtos', 'codproduto'), coalesce((select max("codproduto") from public."produtos"), 1), exists(select 1 from public."produtos"));
select setval(pg_get_serial_sequence('public.servicos', 'codservico'), coalesce((select max("codservico") from public."servicos"), 1), exists(select 1 from public."servicos"));
select setval(pg_get_serial_sequence('public.clientes', 'codcliente'), coalesce((select max("codcliente") from public."clientes"), 1), exists(select 1 from public."clientes"));
select setval(pg_get_serial_sequence('public.fornecedores', 'codfornecedor'), coalesce((select max("codfornecedor") from public."fornecedores"), 1), exists(select 1 from public."fornecedores"));
select setval(pg_get_serial_sequence('public.funcoes_funcionarios', 'codfuncao_funcionario'), coalesce((select max("codfuncao_funcionario") from public."funcoes_funcionarios"), 1), exists(select 1 from public."funcoes_funcionarios"));
select setval(pg_get_serial_sequence('public.funcionarios', 'codfuncionario'), coalesce((select max("codfuncionario") from public."funcionarios"), 1), exists(select 1 from public."funcionarios"));
select setval(pg_get_serial_sequence('public.contas_pagar', 'codconta_pagar'), coalesce((select max("codconta_pagar") from public."contas_pagar"), 1), exists(select 1 from public."contas_pagar"));

commit;
