create table if not exists public.categorias (
	codcategoria integer generated by default as identity primary key,
	categoria varchar(50) not null check (char_length(categoria) between 2 and 50),
	descricao text check (descricao is null or char_length(descricao) <= 255),
	tipo varchar(20) not null default 'AMBOS' check (tipo in ('PRODUTO', 'SERVICO', 'AMBOS')),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'categorias'
			and column_name = 'nome'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'categorias'
			and column_name = 'categoria'
	) then
		alter table public.categorias rename column nome to categoria;
	end if;
end $$;

alter table public.categorias
	drop constraint if exists categorias_nome_check;

alter table public.categorias
	drop constraint if exists categorias_categoria_check;

alter table public.categorias
	alter column categoria type varchar(50);

alter table public.categorias
	add constraint categorias_categoria_check
	check (char_length(categoria) between 2 and 50);

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_categorias_data_ult_alteracao on public.categorias;

create trigger set_categorias_data_ult_alteracao
before update on public.categorias
for each row
execute function public.set_data_ult_alteracao();
