create table if not exists public.categorias (
	codcategoria integer generated by default as identity primary key,
	nome varchar(80) not null check (char_length(nome) between 2 and 80),
	descricao text,
	tipo varchar(20) not null default 'AMBOS' check (tipo in ('PRODUTO', 'SERVICO', 'AMBOS')),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_categorias_data_ult_alteracao on public.categorias;

create trigger set_categorias_data_ult_alteracao
before update on public.categorias
for each row
execute function public.set_data_ult_alteracao();
