create table if not exists public.cidades (
	codcidade integer generated by default as identity primary key,
	cidade varchar(100) not null check (char_length(cidade) between 2 and 100),
	codest integer not null references public.estados(codestado),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_cidades_data_ult_alteracao on public.cidades;

create trigger set_cidades_data_ult_alteracao
before update on public.cidades
for each row
execute function public.set_data_ult_alteracao();
