create table if not exists public.clientes (
	codcliente bigint generated by default as identity primary key,
	tipo text not null check (tipo in ('FISICA', 'JURIDICA')),
	cliente text not null check (char_length(cliente) between 5 and 60),
	apelido text check (apelido is null or char_length(apelido) <= 60),
	estado_civil text check (
		estado_civil is null
		or estado_civil in ('SOLTEIRO', 'CASADO', 'SEPARADO', 'DIVORCIADO', 'VIUVO', 'OUTRO')
	),
	endereco text not null check (char_length(endereco) between 5 and 60),
	numero text not null check (char_length(numero) between 1 and 10),
	complemento text check (complemento is null or char_length(complemento) <= 60),
	bairro text not null check (char_length(bairro) between 5 and 60),
	cep text not null check (char_length(cep) between 8 and 9),
	codcidade bigint not null references public.cidades(codcidade),
	codcondicao_pagamento integer references public.condicoes_pagamento(codcondicao_pagamento),
	telefone text not null check (char_length(telefone) between 5 and 20),
	email text not null check (char_length(email) between 5 and 60),
	sexo text check (sexo is null or sexo in ('MASCULINO', 'FEMININO', 'OUTROS')),
	nacionalidade text check (nacionalidade is null or char_length(nacionalidade) between 5 and 20),
	data_nascimento date,
	rg_inscricao_estadual text check (
		rg_inscricao_estadual is null or char_length(rg_inscricao_estadual) between 5 and 14
	),
	cpf_cnpj text check (cpf_cnpj is null or char_length(cpf_cnpj) between 5 and 14),
	observacoes text check (observacoes is null or char_length(observacoes) <= 255),
	data_criacao timestamptz not null default now(),
	data_atualizacao timestamptz not null default now(),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N'))
);

create or replace function public.set_data_atualizacao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_atualizacao = now();
	return new;
end;
$$;

drop trigger if exists set_clientes_data_atualizacao on public.clientes;

create trigger set_clientes_data_atualizacao
before update on public.clientes
for each row
execute function public.set_data_atualizacao();

alter table public.clientes
add column if not exists codcondicao_pagamento integer;

alter table public.clientes
drop constraint if exists fk_clientes_condicoes_pagamento;

alter table public.clientes
add constraint fk_clientes_condicoes_pagamento
foreign key (codcondicao_pagamento)
references public.condicoes_pagamento(codcondicao_pagamento);
