create table if not exists public.clientes (
	codcliente bigint generated by default as identity primary key,
	tipo text not null check (tipo in ('FISICA', 'JURIDICA')),
	cliente text not null check (char_length(cliente) between 5 and 60),
	apelido text check (apelido is null or char_length(apelido) <= 60),
	estado_civil text check (
		estado_civil is null
		or estado_civil in ('SOLTEIRO', 'CASADO', 'SEPARADO', 'DIVORCIADO', 'VIUVO', 'OUTRO')
	),
	endereco text not null check (char_length(endereco) between 5 and 60),
	numero text not null check (char_length(numero) between 1 and 10),
	complemento text check (complemento is null or char_length(complemento) <= 60),
	bairro text not null check (char_length(bairro) between 5 and 60),
	cep text not null check (char_length(cep) = 8),
	codcidade integer not null references public.cidades(codcidade),
	codcondicao_pagamento integer references public.condicoes_pagamento(codcondicao_pagamento),
	telefone text not null check (char_length(telefone) in (10, 11)),
	contato text check (contato is null or char_length(contato) <= 60),
	email text not null check (char_length(email) between 5 and 60),
	sexo text check (sexo is null or sexo in ('MASCULINO', 'FEMININO', 'OUTROS')),
	nacionalidade text check (nacionalidade is null or char_length(nacionalidade) between 5 and 20),
	data_nascimento date,
	rg_inscricao_estadual text check (
		rg_inscricao_estadual is null or char_length(rg_inscricao_estadual) between 5 and 14
	),
	cpf_cnpj text check (cpf_cnpj is null or char_length(cpf_cnpj) in (11, 14)),
	observacoes text check (observacoes is null or char_length(observacoes) <= 110),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'clientes'
			and column_name = 'data_criacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'clientes'
			and column_name = 'data_cadastro'
	) then
		alter table public.clientes rename column data_criacao to data_cadastro;
	end if;

	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'clientes'
			and column_name = 'data_atualizacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'clientes'
			and column_name = 'data_ult_alteracao'
	) then
		alter table public.clientes rename column data_atualizacao to data_ult_alteracao;
	end if;
end $$;

alter table public.clientes
add column if not exists data_cadastro timestamp not null default current_timestamp;

alter table public.clientes
add column if not exists contato text check (contato is null or char_length(contato) <= 60);

alter table public.clientes
add column if not exists data_ult_alteracao timestamp not null default current_timestamp;

alter table public.clientes
add column if not exists usuario_ult_alteracao integer references public.usuarios(codusuario);

alter table public.clientes
alter column data_cadastro type timestamp using data_cadastro::timestamp,
alter column data_cadastro set default current_timestamp,
alter column data_cadastro set not null,
alter column data_ult_alteracao type timestamp using data_ult_alteracao::timestamp,
alter column data_ult_alteracao set default current_timestamp,
alter column data_ult_alteracao set not null;

drop trigger if exists set_clientes_data_atualizacao on public.clientes;
drop trigger if exists set_clientes_data_ult_alteracao on public.clientes;

create trigger set_clientes_data_ult_alteracao
before update on public.clientes
for each row
execute function public.set_data_ult_alteracao();

alter table public.clientes
add column if not exists codcondicao_pagamento integer;

alter table public.clientes
drop constraint if exists fk_clientes_condicoes_pagamento;

alter table public.clientes
add constraint fk_clientes_condicoes_pagamento
foreign key (codcondicao_pagamento)
references public.condicoes_pagamento(codcondicao_pagamento);
