create table if not exists public.compras (
	codcompra bigint generated by default as identity primary key,
	codfornecedor bigint not null references public.fornecedores(codfornecedor),
	codcondicao_pagamento integer not null references public.condicoes_pagamento(codcondicao_pagamento),
	modelo varchar(10) not null check (char_length(btrim(modelo)) between 1 and 10),
	serie varchar(10) not null check (char_length(btrim(serie)) between 1 and 10),
	numero_nota varchar(30) not null check (char_length(btrim(numero_nota)) between 1 and 30),
	data_emissao date not null,
	data_chegada date not null,
	valor_produtos numeric(14,2) not null check (valor_produtos >= 0),
	valor_frete numeric(14,2) not null default 0 check (valor_frete >= 0),
	valor_seguro numeric(14,2) not null default 0 check (valor_seguro >= 0),
	outras_despesas numeric(14,2) not null default 0 check (outras_despesas >= 0),
	valor_desconto numeric(14,2) not null default 0 check (valor_desconto >= 0),
	valor_total numeric(14,2) not null check (valor_total > 0),
	status varchar(20) not null default 'CONFIRMADA' check (status in ('CONFIRMADA', 'CANCELADA')),
	observacoes text check (observacoes is null or char_length(observacoes) <= 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario),
	check (data_chegada >= data_emissao),
	check (valor_desconto <= valor_produtos + valor_frete + valor_seguro + outras_despesas)
);

create unique index if not exists compras_nota_fornecedor_unique_idx
	on public.compras (
		codfornecedor,
		lower(btrim(modelo)),
		lower(btrim(serie)),
		lower(btrim(numero_nota))
	);

create index if not exists compras_fornecedor_idx
	on public.compras (codfornecedor);

create index if not exists compras_condicao_pagamento_idx
	on public.compras (codcondicao_pagamento);

create table if not exists public.compras_itens (
	codcompra bigint not null,
	num_item integer not null check (num_item >= 1),
	codproduto integer not null,
	quantidade integer not null check (quantidade > 0),
	valor_unitario numeric(14,2) not null check (valor_unitario >= 0),
	valor_desconto numeric(14,2) not null default 0 check (valor_desconto >= 0),
	valor_total numeric(14,2) not null check (valor_total >= 0),
	constraint compras_itens_pkey primary key (codcompra, num_item),
	constraint compras_itens_compra_fkey foreign key (codcompra)
		references public.compras(codcompra) on delete cascade,
	constraint compras_itens_produto_fkey foreign key (codproduto)
		references public.produtos(codproduto),
	constraint compras_itens_produto_unique unique (codcompra, codproduto),
	check (valor_desconto <= quantidade * valor_unitario)
);

create index if not exists compras_itens_produto_idx
	on public.compras_itens (codproduto);

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_compras_data_ult_alteracao on public.compras;

create trigger set_compras_data_ult_alteracao
before update on public.compras
for each row
execute function public.set_data_ult_alteracao();
