create table if not exists public.condicoes_pagamento (
	codcondicao_pagamento integer generated by default as identity primary key,
	condicao_pagamento varchar(50) not null check (char_length(condicao_pagamento) between 2 and 50),
	codforma_pagamento integer,
	prazo_dias integer not null default 0 check (prazo_dias >= 0),
	parcelas integer not null default 1 check (parcelas >= 1),
	juro numeric not null default 0 check (juro >= 0),
	multa numeric not null default 0 check (multa >= 0),
	desconto numeric not null default 0 check (desconto >= 0),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer,
	constraint fk_condpag_usu foreign key (usuario_ult_alteracao) references public.usuarios(codusuario)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'condicoes_pagamento'
			and column_name = 'nome'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'condicoes_pagamento'
			and column_name = 'condicao_pagamento'
	) then
		alter table public.condicoes_pagamento rename column nome to condicao_pagamento;
	end if;
end $$;

alter table public.condicoes_pagamento
	drop constraint if exists condicoes_pagamento_nome_check;

alter table public.condicoes_pagamento
	drop constraint if exists condicoes_pagamento_condicao_pagamento_check;

alter table public.condicoes_pagamento
	alter column condicao_pagamento type varchar(50);

alter table public.condicoes_pagamento
	add constraint condicoes_pagamento_condicao_pagamento_check
	check (char_length(condicao_pagamento) between 2 and 50);

alter table public.condicoes_pagamento
	add column if not exists codforma_pagamento integer;

alter table public.condicoes_pagamento
	drop constraint if exists condicoes_pagamento_codforma_pagamento_fkey;

alter table public.condicoes_pagamento
	add constraint condicoes_pagamento_codforma_pagamento_fkey
	foreign key (codforma_pagamento) references public.formas_pagamento(codforma_pagamento);

create table if not exists public.condicoes_pagamento_parcelas (
	codcondicao_pagamento integer not null,
	num_parcela integer not null check (num_parcela >= 1),
	dias_vencimento integer not null check (dias_vencimento >= 0),
	codforma_pagamento integer not null,
	percentual numeric(7,4) not null check (percentual > 0 and percentual <= 100),
	constraint condicoes_pagamento_parcelas_pkey
		primary key (codcondicao_pagamento, num_parcela),
	constraint condicoes_pagamento_parcelas_condicao_fkey
		foreign key (codcondicao_pagamento)
		references public.condicoes_pagamento(codcondicao_pagamento)
		on delete cascade,
	constraint condicoes_pagamento_parcelas_forma_fkey
		foreign key (codforma_pagamento)
		references public.formas_pagamento(codforma_pagamento)
);

create index if not exists condicoes_pagamento_parcelas_forma_idx
	on public.condicoes_pagamento_parcelas (codforma_pagamento);

insert into public.condicoes_pagamento_parcelas (
	codcondicao_pagamento,
	num_parcela,
	dias_vencimento,
	codforma_pagamento,
	percentual
)
select
	cp.codcondicao_pagamento,
	parcela.num_parcela,
	cp.prazo_dias * parcela.num_parcela,
	cp.codforma_pagamento,
	case
		when parcela.num_parcela = cp.parcelas
			then 100 - round(100.0 / cp.parcelas, 4) * (cp.parcelas - 1)
		else round(100.0 / cp.parcelas, 4)
	end
from public.condicoes_pagamento cp
cross join lateral generate_series(1, cp.parcelas) as parcela(num_parcela)
where cp.codforma_pagamento is not null
on conflict (codcondicao_pagamento, num_parcela) do nothing;

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_condicoes_pagamento_data_ult_alteracao on public.condicoes_pagamento;

create trigger set_condicoes_pagamento_data_ult_alteracao
before update on public.condicoes_pagamento
for each row
execute function public.set_data_ult_alteracao();
