create table if not exists public.condicoes_pagamento (
	codcondicao_pagamento integer generated by default as identity primary key,
	nome varchar(80) not null check (char_length(nome) between 2 and 80),
	prazo_dias integer not null default 0 check (prazo_dias >= 0),
	parcelas integer not null default 1 check (parcelas >= 1),
	juro numeric not null default 0 check (juro >= 0),
	multa numeric not null default 0 check (multa >= 0),
	desconto numeric not null default 0 check (desconto >= 0),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer,
	constraint fk_condpag_usu foreign key (usuario_ult_alteracao) references public.usuarios(codusuario)
);

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_condicoes_pagamento_data_ult_alteracao on public.condicoes_pagamento;

create trigger set_condicoes_pagamento_data_ult_alteracao
before update on public.condicoes_pagamento
for each row
execute function public.set_data_ult_alteracao();
