create table if not exists public.condicoes_pagamento (
	codcondicao_pagamento integer generated by default as identity primary key,
	condicao_pagamento varchar(50) not null check (char_length(condicao_pagamento) between 2 and 50),
	codforma_pagamento integer,
	prazo_dias integer not null default 0 check (prazo_dias >= 0),
	parcelas integer not null default 1 check (parcelas >= 1),
	juro numeric not null default 0 check (juro >= 0),
	multa numeric not null default 0 check (multa >= 0),
	desconto numeric not null default 0 check (desconto >= 0),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer,
	constraint fk_condpag_usu foreign key (usuario_ult_alteracao) references public.usuarios(codusuario)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'condicoes_pagamento'
			and column_name = 'nome'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'condicoes_pagamento'
			and column_name = 'condicao_pagamento'
	) then
		alter table public.condicoes_pagamento rename column nome to condicao_pagamento;
	end if;
end $$;

alter table public.condicoes_pagamento
	drop constraint if exists condicoes_pagamento_nome_check;

alter table public.condicoes_pagamento
	drop constraint if exists condicoes_pagamento_condicao_pagamento_check;

alter table public.condicoes_pagamento
	alter column condicao_pagamento type varchar(50);

alter table public.condicoes_pagamento
	add constraint condicoes_pagamento_condicao_pagamento_check
	check (char_length(condicao_pagamento) between 2 and 50);

alter table public.condicoes_pagamento
	add column if not exists codforma_pagamento integer;

alter table public.condicoes_pagamento
	drop constraint if exists condicoes_pagamento_codforma_pagamento_fkey;

alter table public.condicoes_pagamento
	add constraint condicoes_pagamento_codforma_pagamento_fkey
	foreign key (codforma_pagamento) references public.formas_pagamento(codforma_pagamento);

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_condicoes_pagamento_data_ult_alteracao on public.condicoes_pagamento;

create trigger set_condicoes_pagamento_data_ult_alteracao
before update on public.condicoes_pagamento
for each row
execute function public.set_data_ult_alteracao();
