create table if not exists public.contas_pagar (
	codconta_pagar bigint generated by default as identity primary key,
	conta_pagar varchar(120) not null check (char_length(conta_pagar) between 2 and 120),
	codfornecedor bigint not null references public.fornecedores(codfornecedor),
	codforma_pagamento integer references public.formas_pagamento(codforma_pagamento),
	numero_documento varchar(60) check (numero_documento is null or char_length(numero_documento) <= 60),
	data_emissao date not null default current_date,
	data_vencimento date not null,
	data_pagamento date,
	valor numeric not null check (valor > 0),
	valor_pago numeric not null default 0 check (valor_pago >= 0),
	status varchar(20) not null default 'PENDENTE' check (status in ('PENDENTE', 'PAGO', 'CANCELADO')),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	observacoes text check (observacoes is null or char_length(observacoes) <= 110),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario),
	check (valor_pago <= valor)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'descricao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'conta_pagar'
	) then
		alter table public.contas_pagar rename column descricao to conta_pagar;
	end if;
end $$;

alter table public.contas_pagar
add column if not exists ativo char(1) not null default 'S' check (ativo in ('S', 'N'));

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'data_criacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'data_cadastro'
	) then
		alter table public.contas_pagar rename column data_criacao to data_cadastro;
	end if;

	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'data_atualizacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'contas_pagar'
			and column_name = 'data_ult_alteracao'
	) then
		alter table public.contas_pagar rename column data_atualizacao to data_ult_alteracao;
	end if;
end $$;

alter table public.contas_pagar
add column if not exists data_cadastro timestamp not null default current_timestamp;

alter table public.contas_pagar
add column if not exists data_ult_alteracao timestamp not null default current_timestamp;

alter table public.contas_pagar
add column if not exists usuario_ult_alteracao integer references public.usuarios(codusuario);

alter table public.contas_pagar
alter column data_cadastro type timestamp using data_cadastro::timestamp,
alter column data_cadastro set default current_timestamp,
alter column data_cadastro set not null,
alter column data_ult_alteracao type timestamp using data_ult_alteracao::timestamp,
alter column data_ult_alteracao set default current_timestamp,
alter column data_ult_alteracao set not null;

create index if not exists idx_contas_pagar_fornecedor
on public.contas_pagar(codfornecedor);

create index if not exists idx_contas_pagar_vencimento
on public.contas_pagar(data_vencimento);

drop trigger if exists set_contas_pagar_data_atualizacao on public.contas_pagar;
drop trigger if exists set_contas_pagar_data_ult_alteracao on public.contas_pagar;

create trigger set_contas_pagar_data_ult_alteracao
before update on public.contas_pagar
for each row
execute function public.set_data_ult_alteracao();
