create table if not exists public.estados (
	codestado integer generated by default as identity primary key,
	uf char(2) not null check (char_length(uf) = 2),
	estado varchar(60) not null check (char_length(estado) between 2 and 60),
	codpais integer not null references public.paises(codpais),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_estados_data_ult_alteracao on public.estados;

create trigger set_estados_data_ult_alteracao
before update on public.estados
for each row
execute function public.set_data_ult_alteracao();
