create table if not exists public.formas_pagamento (
	codforma_pagamento integer generated by default as identity primary key,
	forma_pagamento varchar(50) not null unique check (char_length(forma_pagamento) between 2 and 50),
	tipo varchar(20) not null default 'OUTROS' check (
		tipo in ('DINHEIRO', 'PIX', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'BOLETO', 'TRANSFERENCIA', 'OUTROS')
	),
	descricao text check (descricao is null or char_length(descricao) <= 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

alter table public.formas_pagamento
	drop constraint if exists formas_pagamento_forma_pagamento_check;

alter table public.formas_pagamento
	alter column forma_pagamento type varchar(50);

alter table public.formas_pagamento
	add constraint formas_pagamento_forma_pagamento_check
	check (char_length(forma_pagamento) between 2 and 50);

drop trigger if exists set_formas_pagamento_data_ult_alteracao on public.formas_pagamento;

create trigger set_formas_pagamento_data_ult_alteracao
before update on public.formas_pagamento
for each row execute function public.set_data_ult_alteracao();
