create table if not exists public.fornecedores (
	codfornecedor bigint generated by default as identity primary key,
	tipo text not null check (tipo in ('FISICA', 'JURIDICA')),
	fornecedor text not null check (char_length(fornecedor) between 5 and 80),
	nome_fantasia text check (nome_fantasia is null or char_length(nome_fantasia) <= 80),
	contato text check (contato is null or char_length(contato) <= 60),
	endereco text not null check (char_length(endereco) between 5 and 80),
	numero text not null check (char_length(numero) between 1 and 10),
	complemento text check (complemento is null or char_length(complemento) <= 60),
	bairro text not null check (char_length(bairro) between 5 and 60),
	cep text not null check (char_length(cep) = 8),
	codcidade integer not null references public.cidades(codcidade),
	telefone text not null check (char_length(telefone) in (10, 11)),
	email text not null check (char_length(email) between 5 and 80),
	rg_inscricao_estadual text check (
		rg_inscricao_estadual is null or char_length(rg_inscricao_estadual) between 5 and 14
	),
	cpf_cnpj text check (cpf_cnpj is null or char_length(cpf_cnpj) in (11, 14)),
	observacoes text check (observacoes is null or char_length(observacoes) <= 255),
	data_criacao timestamptz not null default now(),
	data_atualizacao timestamptz not null default now(),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N'))
);

drop trigger if exists set_fornecedores_data_atualizacao on public.fornecedores;

create trigger set_fornecedores_data_atualizacao
before update on public.fornecedores
for each row
execute function public.set_data_atualizacao();
