create table if not exists public.fornecedores (
	codfornecedor bigint generated by default as identity primary key,
	tipo text not null check (tipo in ('FISICA', 'JURIDICA')),
	fornecedor text not null check (char_length(fornecedor) between 5 and 80),
	nome_fantasia text check (nome_fantasia is null or char_length(nome_fantasia) <= 80),
	contato text check (contato is null or char_length(contato) <= 60),
	endereco text not null check (char_length(endereco) between 5 and 80),
	numero text not null check (char_length(numero) between 1 and 10),
	complemento text check (complemento is null or char_length(complemento) <= 60),
	bairro text not null check (char_length(bairro) between 5 and 60),
	cep text not null check (char_length(cep) = 8),
	codcidade integer not null references public.cidades(codcidade),
	telefone text not null check (char_length(telefone) in (10, 11)),
	email text not null check (char_length(email) between 5 and 80),
	rg_inscricao_estadual text check (
		rg_inscricao_estadual is null or char_length(rg_inscricao_estadual) between 5 and 14
	),
	cpf_cnpj text check (cpf_cnpj is null or char_length(cpf_cnpj) in (11, 14)),
	observacoes text check (observacoes is null or char_length(observacoes) <= 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'nome'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'fornecedor'
	) then
		alter table public.fornecedores rename column nome to fornecedor;
	end if;

	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'data_criacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'data_cadastro'
	) then
		alter table public.fornecedores rename column data_criacao to data_cadastro;
	end if;

	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'data_atualizacao'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'fornecedores'
			and column_name = 'data_ult_alteracao'
	) then
		alter table public.fornecedores rename column data_atualizacao to data_ult_alteracao;
	end if;
end $$;

alter table public.fornecedores
add column if not exists data_cadastro timestamp not null default current_timestamp;

alter table public.fornecedores
add column if not exists data_ult_alteracao timestamp not null default current_timestamp;

alter table public.fornecedores
add column if not exists usuario_ult_alteracao integer references public.usuarios(codusuario);

alter table public.fornecedores
alter column data_cadastro type timestamp using data_cadastro::timestamp,
alter column data_cadastro set default current_timestamp,
alter column data_cadastro set not null,
alter column data_ult_alteracao type timestamp using data_ult_alteracao::timestamp,
alter column data_ult_alteracao set default current_timestamp,
alter column data_ult_alteracao set not null;

drop trigger if exists set_fornecedores_data_atualizacao on public.fornecedores;
drop trigger if exists set_fornecedores_data_ult_alteracao on public.fornecedores;

create trigger set_fornecedores_data_ult_alteracao
before update on public.fornecedores
for each row
execute function public.set_data_ult_alteracao();
