create table if not exists public.funcionarios (
	codfuncionario integer generated by default as identity primary key,
	funcionario varchar(80) not null check (char_length(funcionario) between 5 and 80),
	apelido varchar(60) check (apelido is null or char_length(apelido) <= 60),
	codfuncao_funcionario integer not null references public.funcoes_funcionarios(codfuncao_funcionario),
	telefone varchar(11) not null check (char_length(telefone) in (10, 11)),
	email varchar(80) check (email is null or char_length(email) between 5 and 80),
	cpf varchar(11) not null unique check (char_length(cpf) = 11),
	rg varchar(14) check (rg is null or char_length(rg) between 5 and 14),
	data_nascimento date,
	data_admissao date not null default current_date,
	salario_base numeric not null default 0 check (salario_base >= 0),
	percentual_comissao numeric not null default 0 check (percentual_comissao between 0 and 100),
	observacoes text check (observacoes is null or char_length(observacoes) <= 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'funcionarios'
			and column_name = 'cargo'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'funcionarios'
			and column_name = 'codfuncao_funcionario'
	) then
		insert into public.funcoes_funcionarios (funcao_funcionario)
		select distinct trim(cargo)
		from public.funcionarios
		where cargo is not null
			and trim(cargo) <> ''
		on conflict (funcao_funcionario) do nothing;

		alter table public.funcionarios
		add column codfuncao_funcionario integer references public.funcoes_funcionarios(codfuncao_funcionario);

		update public.funcionarios f
		set codfuncao_funcionario = ff.codfuncao_funcionario
		from public.funcoes_funcionarios ff
		where ff.funcao_funcionario = trim(f.cargo);

		alter table public.funcionarios
		alter column codfuncao_funcionario set not null;

		alter table public.funcionarios
		drop column cargo;
	end if;
end $$;

drop trigger if exists set_funcionarios_data_ult_alteracao on public.funcionarios;

create trigger set_funcionarios_data_ult_alteracao
before update on public.funcionarios
for each row execute function public.set_data_ult_alteracao();
