create table if not exists public.funcoes_funcionarios (
	codfuncao_funcionario integer generated by default as identity primary key,
	funcao_funcionario varchar(60) not null unique check (char_length(funcao_funcionario) between 2 and 60),
	descricao text check (descricao is null or char_length(descricao) <= 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

drop trigger if exists set_funcoes_funcionarios_data_ult_alteracao on public.funcoes_funcionarios;

create trigger set_funcoes_funcionarios_data_ult_alteracao
before update on public.funcoes_funcionarios
for each row execute function public.set_data_ult_alteracao();
