create table if not exists public.marcas (
	codmarca integer generated by default as identity primary key,
	marca varchar(40) not null unique check (char_length(marca) between 2 and 40),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

alter table public.marcas
	drop constraint if exists marcas_marca_check;

alter table public.marcas
	alter column marca type varchar(40);

alter table public.marcas
	add constraint marcas_marca_check
	check (char_length(marca) between 2 and 40);

alter table public.marcas
	drop constraint if exists marcas_descricao_check;

alter table public.marcas
	drop column if exists descricao;

drop trigger if exists set_marcas_data_ult_alteracao on public.marcas;

create trigger set_marcas_data_ult_alteracao
before update on public.marcas
for each row execute function public.set_data_ult_alteracao();
