create table if not exists public.marcas (
	codmarca integer generated by default as identity primary key,
	marca varchar(80) not null unique check (char_length(marca) between 2 and 80),
	descricao text check (descricao is null or char_length(descricao) <= 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

drop trigger if exists set_marcas_data_ult_alteracao on public.marcas;

create trigger set_marcas_data_ult_alteracao
before update on public.marcas
for each row execute function public.set_data_ult_alteracao();
