create table if not exists public.paises (
	codpais integer generated by default as identity primary key,
	pais varchar(60) not null check (char_length(pais) between 2 and 60),
	sigla varchar(5) check (sigla is null or char_length(sigla) <= 5),
	ddi varchar(5) check (ddi is null or char_length(ddi) <= 5),
	moeda varchar(10) check (moeda is null or char_length(moeda) <= 10),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_paises_data_ult_alteracao on public.paises;

create trigger set_paises_data_ult_alteracao
before update on public.paises
for each row
execute function public.set_data_ult_alteracao();
