create table if not exists public.produtos (
	codproduto integer generated by default as identity primary key,
	produto varchar(40) not null check (char_length(produto) between 2 and 40),
	codcategoria integer references public.categorias(codcategoria),
	codmarca integer references public.marcas(codmarca),
	codunidade_medida integer references public.unidades_medida(codunidade_medida),
	valor numeric not null default 0 check (valor >= 0),
	quantidade_estoque integer not null default 0 check (quantidade_estoque >= 0),
	valor_desconto numeric default 0 check (valor_desconto >= 0),
	descricao text check (descricao is null or char_length(descricao) <= 100),
	imagem_url text,
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario),
	check (valor_desconto <= valor)
);

alter table public.produtos
	drop constraint if exists produtos_produto_check;

alter table public.produtos
	alter column produto type varchar(40);

alter table public.produtos
	add constraint produtos_produto_check
	check (char_length(produto) between 2 and 40);

alter table public.produtos
	drop constraint if exists produtos_descricao_check;

alter table public.produtos
	add constraint produtos_descricao_check
	check (descricao is null or char_length(descricao) <= 100);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'produtos'
			and column_name = 'nome'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'produtos'
			and column_name = 'produto'
	) then
		alter table public.produtos rename column nome to produto;
	end if;
end $$;

alter table public.produtos
	add column if not exists codmarca integer;

alter table public.produtos
	add column if not exists codunidade_medida integer;

alter table public.produtos
	drop constraint if exists produtos_codmarca_fkey;

alter table public.produtos
	add constraint produtos_codmarca_fkey foreign key (codmarca) references public.marcas(codmarca);

alter table public.produtos
	drop constraint if exists produtos_codunidade_medida_fkey;

alter table public.produtos
	add constraint produtos_codunidade_medida_fkey foreign key (codunidade_medida) references public.unidades_medida(codunidade_medida);

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_produtos_data_ult_alteracao on public.produtos;

create trigger set_produtos_data_ult_alteracao
before update on public.produtos
for each row
execute function public.set_data_ult_alteracao();
