create table if not exists public.servicos (
	codservico integer generated by default as identity primary key,
	servico varchar(50) not null check (char_length(servico) between 2 and 50),
	codcategoria integer references public.categorias(codcategoria),
	duracao_minutos integer not null check (duracao_minutos > 0),
	valor numeric not null default 0 check (valor >= 0),
	valor_desconto numeric default 0 check (valor_desconto >= 0),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario),
	check (valor_desconto <= valor)
);

do $$
begin
	if exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'servicos'
			and column_name = 'nome'
	) and not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'servicos'
			and column_name = 'servico'
	) then
		alter table public.servicos rename column nome to servico;
	end if;
end $$;

alter table public.servicos
	drop constraint if exists servicos_nome_check;

alter table public.servicos
	drop constraint if exists servicos_servico_check;

alter table public.servicos
	alter column servico type varchar(50);

alter table public.servicos
	add constraint servicos_servico_check
	check (char_length(servico) between 2 and 50);

alter table public.servicos
	drop constraint if exists servicos_descricao_check;

alter table public.servicos
	drop column if exists descricao;

alter table public.servicos
	drop column if exists imagem_url;

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_servicos_data_ult_alteracao on public.servicos;

create trigger set_servicos_data_ult_alteracao
before update on public.servicos
for each row
execute function public.set_data_ult_alteracao();
