create table if not exists public.servicos (
	codservico integer generated by default as identity primary key,
	nome varchar(150) not null check (char_length(nome) between 2 and 150),
	codcategoria integer references public.categorias(codcategoria),
	duracao_minutos integer not null check (duracao_minutos > 0),
	valor numeric not null default 0 check (valor >= 0),
	valor_desconto numeric default 0 check (valor_desconto >= 0),
	descricao text,
	imagem_url text,
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario),
	check (valor_desconto <= valor)
);

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_servicos_data_ult_alteracao on public.servicos;

create trigger set_servicos_data_ult_alteracao
before update on public.servicos
for each row
execute function public.set_data_ult_alteracao();
