create table if not exists public.unidades_medida (
	codunidade_medida integer generated by default as identity primary key,
	unidade_medida varchar(40) not null unique check (char_length(unidade_medida) between 2 and 40),
	sigla varchar(10) not null unique check (char_length(sigla) between 1 and 10),
	descricao text check (descricao is null or char_length(descricao) <= 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

alter table public.unidades_medida
	drop constraint if exists unidades_medida_unidade_medida_check;

alter table public.unidades_medida
	alter column unidade_medida type varchar(40);

alter table public.unidades_medida
	add constraint unidades_medida_unidade_medida_check
	check (char_length(unidade_medida) between 2 and 40);

insert into public.unidades_medida (unidade_medida, sigla, descricao)
values
	('Unidade', 'UN', 'Produto vendido por unidade'),
	('Mililitro', 'ML', 'Produto medido em mililitros'),
	('Grama', 'G', 'Produto medido em gramas')
on conflict (sigla) do nothing;

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_unidades_medida_data_ult_alteracao on public.unidades_medida;

create trigger set_unidades_medida_data_ult_alteracao
before update on public.unidades_medida
for each row
execute function public.set_data_ult_alteracao();

alter table public.produtos
	add column if not exists codunidade_medida integer;

alter table public.produtos
	drop constraint if exists produtos_codunidade_medida_fkey;

alter table public.produtos
	add constraint produtos_codunidade_medida_fkey foreign key (codunidade_medida) references public.unidades_medida(codunidade_medida);
