create table if not exists public.usuarios (
	codusuario integer generated by default as identity primary key,
	usuario varchar(50) not null check (char_length(usuario) between 3 and 50),
	senha varchar(255) not null check (char_length(senha) between 6 and 255),
	ativo char(1) not null default 'S' check (ativo in ('S', 'N')),
	data_cadastro timestamp not null default current_timestamp,
	data_ult_alteracao timestamp not null default current_timestamp,
	usuario_ult_alteracao integer references public.usuarios(codusuario)
);

create or replace function public.set_data_ult_alteracao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.data_ult_alteracao = current_timestamp;
	return new;
end;
$$;

drop trigger if exists set_usuarios_data_ult_alteracao on public.usuarios;

create trigger set_usuarios_data_ult_alteracao
before update on public.usuarios
for each row
execute function public.set_data_ult_alteracao();
